name: 01 - Building Blocks

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful Step
        run: | # this vertical bar is necessary to write a multi-line script
          echo "I succeeded"
          exit 0

      - name: Say Goodbye
        run: echo "Goodbye, world!"
