name: 03 - Workflow Runners

on:
  push:
    branches:
      - main

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on $RUNNER_OS"
          echo "Runner Name: $RUNNER_NAME"

  macos-runner:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on $RUNNER_OS"
          echo "Runner Name: $RUNNER_NAME"

  windows-runner:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash # for windows has to instruct the action to run the commands on a bash shell
        run: |
          echo "This job is running on $RUNNER_OS"
          echo "Runner Name: $RUNNER_NAME"
