name: 06 - Contexts

run-name: 06 - Contexts | DEBUG = ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: "My workflow variable"
  MY_OVERWRITTEN_VAR: "This is the overwritten value from the workflow"

jobs:
  echo-data:
    env:
      MY_JOB_VAR: "My job variable"
      MY_OVERWRITTEN_VAR: "This is the overwritten value from the job"
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow ref: ${{ github.workflow_ref }}"
          echo "Workflow sha: ${{ github.workflow_sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Run attempt: ${{ github.run_attempt }}"

      - name: Retrieve Variables
        run: |
          echo "Custom variable value: ${{ vars.CUSTOM_VAR }}"

      - name: Display ENV variables
        env:
          MY_STEP_VAR: "My step variable"
          MY_OVERWRITTEN_VAR: "This is the overwritten value from the step"
        run: |
          echo "MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
          echo "MY_JOB_VAR: ${{ env.MY_JOB_VAR }}"
          echo "MY_STEP_VAR: ${{ env.MY_STEP_VAR }}"
          echo "MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
