name: 08 - Variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env variable"
  OVERWRITTEN_VAR: ${{ vars.OVERWRITTEN_VAR || 'default overwritten var' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env variable"
    steps:
      - name: Print ENV Variables
        env:
          STEP_VAR: "I am a step env variable"
          step_var2: "I am another step env variable" # the ENV variables doesn't have to always be upper case
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: ${{ env.step_var2 }}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"

  echo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository Variables
        run: |
          echo "Repository var: ${{ vars.CUSTOM_REPO_VAR }}"

  echo-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print production Variables
        run: |
          echo "Target var: ${{ vars.TARGET_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"

  echo-dev:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Print develop Variables
        run: |
          echo "Target var: ${{ vars.TARGET_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN_VAR }}"
