name: 09 - Using Functions

on:
  workflow_dispatch:

jobs:
  echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "PR title ${{ github.event.pull_request.title }}"

      - name: Print PR labels
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF

      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: echo "I am a bug fix"

      - name: I will be executed
        if: ${{ success() }}
        run: echo "I will print if previous steps succeed"

      - name: I will be skipped
        if: ${{ failure() }}
        run: echo "I will print if previous steps failed"

      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if workflow is cancelled"

      - name: I will execute when not cancelled
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled"
