name: 10 - Execution Flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: "Whether the unit tests will pass or not"
        default: true

defaults:
  run:
    working-directory: 04-using-actions/react-app

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    # continue-on-error: true - this will make the workflow continue and even mark the workflow as successful even if this job fails
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        if: ${{ inputs.pass-unit-tests }}
        run: npm run test

      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1

  deploy-staging:
    needs:
      - lint-build
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Deploy to staging
        run: npm run deploy:staging

  e2e-tests:
    needs:
      - deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run e2e

  deploy-prod:
    needs:
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Deploy to production
        run: npm run deploy:prod
