name: 12 - Working with outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: boolean
        description: "Whether the build was successful"
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}
      mistake: ${{ steps.build.outputs.mistake }}

    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"

      - name: Build
        id: build
        run: |
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"

      - name: Mistake
        run: | # override the $GITHUB_OUTPUT file content with `>`
          echo "mistake=true" > "$GITHUB_OUTPUT"  
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'true' }}
    steps:
      - name: Deploy
        run: echo "Deployed successfully"

      - name: Print outputs
        run: |
          echo "output1: ${{ needs.build.outputs.output1 }}"
          echo "output2: ${{ needs.build.outputs.output2 }}"
          echo "mistake: ${{ needs.build.outputs.mistake }}"
