name: 12 - Working with outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: boolean
        description: "Whether the build was successful"
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"

      - name: Build
        id: build
        run: |
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'true' }}
    steps:
      - name: Deploy
        run: echo "Deployed successfully"
