name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "Whether to execute cache steps"
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app

    # 1. Checkout the code - to interact with the files of the codebase
    # 2. Install dependencies
    # 3. Execute linting, formatting, unit testing and building
    # 4. Deploy to a non-prod environment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy to non-prod
        run: npm run deploy:non-prod
