name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "Whether to execute cache steps"
        default: true
      node-version:
        type: choice
        description: "The Node.js version to use"
        options:
          - "18.x"
          - "20.x"
          - "21.x"
        default: "20.x"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}

    # 1. Checkout the code - to interact with the files of the codebase
    # 2. Install dependencies
    # 3. Execute linting, formatting, unit testing and building
    # 4. Deploy to a non-prod environment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"

      - name: Download cached dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        if: ${{ inputs.use-cache }}
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}

      - name: Install dependencies
        if: steps.cache-key.outputs.CACHE_KEY != 'true'
        run: npm ci

  lint-format-test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        if: ${{ inputs.use-cache }}
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-dependencies.outputs.deps-cache-key }}

      - name: Install dependencies
        if: needs.install-dependencies.outputs.deps-cache-key.cache-hit != 'true'
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

  build-deploy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-dependencies.outputs.deps-cache-key }}

      - name: Install dependencies
        if: needs.install-dependencies.outputs.deps-cache-key.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to non-prod
        run: npm run deploy:non-prod
