name: 14 - Working with Artifacts

on:
  workflow_dispatch:

env:
  build-artifact-key: "app-${{ github.sha }}"
  test-report-key: "test-coverage-${{ github.sha }}"

jobs:
  test-build: # upload artifacts
    name: Test and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download cached dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test
        run: npm run test -- --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-report-key }}
          path: 14-artifacts/react-app/coverage

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: 14-artifacts/react-app/build

  deploy: # download artifacts
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: build

      - name: Show folder structure
        run: ls -R
