name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backward-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      fail-fast: false # default value is true: if one failed, all the subsequent jobs will be cancelled
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 18.x]
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experiment
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fail is experimental
        if: ${{ matrix.tag == 'experiment' }}
        run: |
          echo "This is an experimental version"
          exit 1

      - name: Perform some tests
        run: |
          echo "Running tests for OS ${{ matrix.os }} and Node.js: ${{ matrix.node-version }}"
          sleep 10

      - name: Upload test results
        run: echo "Uploading test results"

  include-example:
    name: ${{ matrix.shape }}-${{ matrix.color }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shape: [circle, square]
        color: [red, green]
        size: [small, large]
        include:
          - shape: circle
            color: blue
    steps:
      - name: Dummy step
        run: echo "${{ matrix.shape }}-${{ matrix.color }}-${{ matrix.size }}"
