name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backward-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      fail-fast: false # default value is true: if one failed, all the subsequent jobs will be cancelled
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 18.x]
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experiment
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform some tests
        run: |
          echo "Running tests for OS ${{ matrix.os }} and Node.js: ${{ matrix.node-version }}"

      - name: Upload test results
        run: echo "Uploading test results"

  include-example:
    name: ${{ matrix.shape }}-${{ matrix.color }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shape: [circle, square]
        color: [red, green]
        size: [small, large]
        exclude: # exclude is taken into account before include
          - color: green # will exclude all green circles small / large
            shape: circle
        include:
          - opacity: 0.5
          - color: red
            opacity: 0.8
          - shape: circle
            opacity: 0.9
          - shape: triangle
            color: red
          - color: green # will include large green circles back
            shape: circle
            size: large
    steps:
      - name: Dummy step
        run: echo "${{ matrix.shape }}-${{ matrix.color }}-${{ matrix.size }}-${{ matrix.opacity }}"
