name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backward-compatibility:
    name: Backward compatibility ${{ matrix.os }}-${{ matrix.node-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 18.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform some tests
        run: |
          echo "Running tests for OS ${{ matrix.os }} and Node.js: ${{ matrix.node-version }}"
