name: 16 - Working with environments

on:
  workflow_dispatch:

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    environment: develop
    env:
      BASE_URL: ${{ vars.BASE_URL || 'https://example.com' }}
    steps:
      - name: Deploy develop
        run: echo "deploying to ${{ env.BASE_URL }}"

  e2e-tests:
    runs-on: ubuntu-latest
    environment: develop
    needs: deploy-develop
    steps:
      - name: Run e2e tests
        run: echo "Running e2e tests"

  echo-prod-backend:
    name: Deploy production backend
    runs-on: ubuntu-latest
    environment: production
    needs: e2e-tests
    env:
      BASE_URL: ${{ vars.BASE_URL || 'https://example.com' }}
    steps:
      - name: Echo production base url
        run: echo "The production base url is ${{ env.BASE_URL }}"

  echo-prod-frontend:
    name: Deploy production frontend
    runs-on: ubuntu-latest
    environment: production
    needs: e2e-tests
    env:
      BASE_URL: ${{ vars.BASE_URL || 'https://example.com' }}
    steps:
      - name: Echo production base url
        run: echo "The production base url is ${{ env.BASE_URL }}"
