name: 17.1 Custom Actions - Composite
run-name: "17.1 Custom Actions - Composite | ${{ inputs.target-env }}"

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which environment to target
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and NPM dependencies
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with: # inputs for the custom action
          node-version: 20.x
          working-directory: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}

      - name: Print setup deps output
        run: |
          echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"
          echo "Random output: ${{ steps.setup-deps.outputs.random-output }}"

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
