name: 17.3 Custom Actions - Docker
run-name: 17.3 Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: "The URL to ping"
        default: https://www.google.com

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
