name: 18.2 - Reusable workflows - reusable workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dir

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "Deploy URL: ${{ needs.deploy.outputs.deploy-url }}"
