name: 18.3 - Reusable workflows - reusable workflow with secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dir

  e2e-tests:
    uses: sudeshnt/github-actions-reusable-workflow/.github/workflows/e2e.yaml@main
    needs: deploy
    secrets:
      access-token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "Deploy URL: ${{ needs.deploy.outputs.deploy-url }}"
